### ISSUE TITLE
how i can use this product

### ISSUE THREAD

**Issue by glerinsonum** [liushengxian/soup-js#2]
@liushengxian

**Comment by glerinsonum** [comment]
![213](https://user-images.githubusercontent.com/21057103/30346276-91b4e284-9808-11e7-8414-97dcb812b944.PNG)

**Comment by liushengxian** [comment]
Sorry, run 'npm install' under the folder before you want to run this flood.js. And you need buy some phone numbers from Twilio(www.twilio.com).
